spring:

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

  rabbitmq:
    host: ${rabbitmq_host}
    port: 61613

    logging:
      level:
        org:
          springframework: INFO